### ISSUE TITLE
Crystal spec support

### ISSUE THREAD

**Issue by veelenga** [rhysd/vim-crystal#18]
@rhysd Thanks for the work. It is great. 

I really enjoy running specs within vim via [vim-rspec](https://github.com/thoughtbot/vim-rspec). Don't we want to be able to run Crystal's built-in spec with vim-crystal ?

**Comment by rhysd** [comment]
Sounds good.  I'll consider it.

**Comment by rhysd** [comment]
Although there many improve points, I added first support of `crystal spec` as [descibed in README](https://github.com/rhysd/vim-crystal#spec-integration)

**Comment by veelenga** [comment]
Looks great and as usual very quickly. I have just tried it and works as described. Thanks!

The last thing I would like to have here is running individual specs. From Crystal's [Spec](http://crystal-lang.org/api/Spec.html) doc:

> In addition, you can also run individual specs by optionally providing a line number:
> 
>   crystal spec spec/my/test/file_spec.cr:14

Sometimes this useful when using TDD approach and have a lot of specs for current buffer.
What do you think ?

**Comment by rhysd** [comment]
> Sometimes this useful when using TDD approach and have a lot of specs for current buffer.
> What do you think ?

Oh, I didn't know line option of `spec` subcommand.
I think `:CrystalSpecCurrent` should run the spec under the cursor casually.  I'll modify for it.

**Comment by rhysd** [comment]
@veelenga 

I modified the behavior of `:CrystalSpecRunCurrent`.

https://github.com/rhysd/vim-crystal#crystalspecruncurrent-mapping-to-gsc
1. When current buffer is a spec source, `:CrystalSpecRunCurrent` runs the spec under the cursor.  You should execute this command after moving cursor to `it ... do` line or `describe ... do` line.
2. When current buffer is not a spec source, `:CrystalSpecRunCurrent` finds corresponding spec source and runs all specs in the source.

The behavior got a bit complex, but this is better behavior when many specs exists in the spec file as you said.
Note that when current buffer is not a spec source, it runs all corresponding specs because vim-crystal can't know which spec should be run.

**Comment by veelenga** [comment]
Thank you! It's awesome. As for me it's very convenient and useful.

I am sure you know but just want to mention about  [vim-dispatch](https://github.com/tpope/vim-dispatch) that can help to deal with long running specs in vim-crystal. Maybe you can suggest how to integrate...

Thanks again for the implementation.

**Comment by rhysd** [comment]
Thank you for your confirmation.

I don't use vim-dispatch but I'll welcome vim-dispatch support PR.  Please note that default behavior should not be changed.
