### ISSUE TITLE
commands and complete don't work with vim-polyglot

### ISSUE THREAD

**Issue by jinyeow** [rhysd/vim-crystal#45]
vim-polyglot adds lines:
```
if !exists('g:polyglot_disabled') || index(g:polyglot_disabled, 'crystal') == -1
...
endif
```
above and below what's in `crystal.vital`.

`vital.vim` has a line `return vital#_{substitute(ver[0], '\W', '', 'g')}#new()` which looks at the first line in the file.

However, because vim-polyglot added those lines, it breaks vim-crystal and produces errors.

I was wondering if the first line in `crystal.vital` ever changed from 'crystal'. 

If it doesn't, then there doesn't seem to be a need to read from the first line of the file and we can just use the `a:name` passed into the function `vital#of()`, which is 'crystal', to do the same thing.

This would preserve the functionality when vim-crystal is installed via vim-polyglot.

What are your thoughts on this change?

**Comment by rhysd** [comment]
Thank you for your report.

I updated vital modules at df55053. Module loader was also updated and now it loads vital modules in different way. I'm not sure that it fixes this issue, tho (because I'm not vim-polyglot user).

Anyway, I can't say that vim-crystal supports all Vim distributions' hacky behaviors such as:

> vim-polyglot adds lines:

This plugin does not assume that it is modified after installation.

In addition, it should be a bug of vim-polyglot. `crystal.vital` file is not a Vim script source code. It can obviously be distinguished by file extension `.vital`. But vim-polyglot ignores it and forces to modify the file. I won't add any code to support such a behavior.
