### ISSUE TITLE
Setting the compiler command to `bin/crystal` breaks the code on `:CrystalFormat`

### ISSUE THREAD

**Issue by bew** [rhysd/vim-crystal#69]
When I set `g:crystal_compiler_command` to `bin/crystal`, `:CrystalFormat` breaks my code by also inserting the line ``^[[33mUsing compiled compiler at `.build/crystal'^[[0m`` on top of the file.

The offending line is written to stderr, so there should be an easy way to ignore stderr when reading the output of the compiler.

**Comment by rhysd** [comment]
I *guess* you assume crystal-lang/crystal repository. `bin/crystal` is [a wrapper script](https://github.com/crystal-lang/crystal/blob/master/bin/crystal), not a `crystal` command itself. So `g:crystal_compiler_command` does not consider it. Actual built binary is put at `.build/crystal` so please use it rather than the wrapper script.

**Comment by bew** [comment]
> So g:crystal_compiler_command does not consider it.

It actually works, it's just that stderr (with the stdlib message) is also inserted on the top of the formatted file. 

---

Thanks for answering, I know it's a wrapper, it uses the built crystal when available or fallback to system install of crystal. 
It also sets a few environments variables for me and points to the correct stdlib (not the system's).

So to have all of that, I'd have to write another wrapper script similar to `bin/crystal` that doesn't print anything to stderr.

I was thinking about an alternative that I think is more generic: ignore stderr for `:CrystalFormat` (and maybe display it if the command ends with a non-zero status).

What do you think?

**Comment by rhysd** [comment]
Since the message is output to stdout, I think it is intended that formatter does not work. The `crystal tool format` command outputs formatted code to stdout. So there is a conflict between `bin/crystal` and `crystal tool format`, meant that vim-crystal has nothing to do with.

I think it's the best way to improve the `build/crystal` script. For example: Add `$BIN_CRYSTAL_SUPPRESS_WARNING` environment variable and suppress the warning message when it is set. Modification would be easy so you'd be able to quickly propose it by making a PR. Referring this issue would be useful to explain why it is necessary.

**Comment by bew** [comment]
I just checked, the message is output to stderr, as you can see in this little example:
![cr_format](https://user-images.githubusercontent.com/9730330/74610354-fa4ed700-50f2-11ea-9235-42ac7885bff5.png)

**Comment by rhysd** [comment]
Oh, you're correct.

https://github.com/crystal-lang/crystal/blob/81f728bdead9f43c19561b09ef77386c5fccdf21/bin/crystal#L129

I think we can redirect stderr to suppress it.

**Comment by rhysd** [comment]
If you have time, would you try f87af4e? stderr now should be redirected to `/dev/null` (or `nul` on Windows) so this issue should be fixed

**Comment by bew** [comment]
Thanks! The change looks good, I'll check later today on my computer

**Comment by bew** [comment]
It works well :ok_hand:
